FROM php:7.4-apache

RUN docker-php-ext-install mysqli pdo pdo_mysql

RUN apt-get update && apt-get install -y curl \
    && curl -sS https://getcomposer.org/installer | php -- \
       --install-dir=/usr/local/bin \
       --filename=composer

WORKDIR /var/www/html

COPY . /var/www/html

RUN a2enmod rewrite

EXPOSE 80
CMD ["apache2-foreground"]
